"""Emit the per-project artifacts: manifest, guard, hooks, thin AGENTS.md, CLAUDE.md.

Design rules that came straight out of the plan reviews:
  - AGENTS.md stays THIN (EXTENDING.md Rule 2): it names the pillars that apply and the one
    hard rule, and defers all depth to the skills. It never inlines skill content.
  - .claude/settings.json is MERGED, not overwritten: an existing hook set is preserved and
    the mir hook is reconciled to the desired shape, so re-running is idempotent.
  - Every generated file carries an ownership marker so a human and a re-run both know mir
    owns it. Content below the marker is preserved on regeneration, in EVERY artifact that
    offers a tail -- the marker is an address, not a flag.
  - Nothing is written to a destination that has not been inspected first. Every write
    target is classified (absent / mir-owned / unowned / symlink / non-regular /
    unparseable) BEFORE the first byte lands, and a destination mir does not own aborts the
    whole run. A partial harness is worse than none, because it looks installed.
  - --dry-run prints the diff of what would change and writes nothing -- including no
    backups, which is why refusal is decided in plan() and executed in apply().
"""

from __future__ import annotations

import copy
import json
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
import schema  # noqa: E402


class GenerateError(Exception):
    """A destination could not be written safely, so nothing was written.

    Raised before any byte is emitted -- a symlinked destination that would truncate a
    file outside the repo, a settings.json that will not parse, or a human-owned file
    mir does not own. Generation is all-or-nothing on purpose: a partial harness is
    worse than none, because it looks installed. The CLI turns this into exit 3, the
    same code it already uses for "you must decide something".
    """

MARK = "generated by mir init"
HOOK_TAG = "mir-init-guard"
MATCHER = "Write|Edit|MultiEdit|NotebookEdit|Update|Bash"

# The end of the mir-owned region in any text artifact. Everything after it belongs to the
# human and survives regeneration. It is a single constant rather than a per-file rule so
# that a new artifact gets tail preservation by emitting the line, not by editing a list.
TAIL_MARK = "preserved across regenerations. -->"
TAIL_LINE = "<!-- Anything you write BELOW this line is preserved across regenerations. -->"


# -- destination safety -----------------------------------------------------------------
# apply() used to be makedirs + open(dest, "w"), which cannot tell an absent file from a
# symlink into $HOME, so it truncated whatever the link pointed at. Every destination is
# now classified first, and the classification -- not the filename -- decides the write.

ABSENT = "absent"              # nothing there: write it
MIR_OWNED = "mir_owned"        # a file mir wrote: rewrite it
UNOWNED = "unowned"            # a real file with no mir ownership evidence: refuse
SYMLINK = "symlink"            # a link (live OR dangling): refuse, never follow
NON_REGULAR = "non_regular"    # directory, fifo, device, unreadable: refuse
UNPARSEABLE = "unparseable"    # a merge target mir cannot read back: refuse

# Refusing on UNPARSEABLE is the point of finding 6: a settings.json that will not parse was
# treated as absent, so every hook the user had was silently replaced by mir's one hook.
REFUSING = (UNOWNED, SYMLINK, NON_REGULAR, UNPARSEABLE)

# Only a regular file whose bytes we are refusing to overwrite gets copied aside. A symlink
# or a device node is NOT backed up: reading it is the exact hazard the refusal exists for.
BACKED_UP = (UNOWNED, UNPARSEABLE)


class Disposition:
    """What is at a destination, and therefore what mir is allowed to do with it."""

    def __init__(self, state: str, rel: str, path: str, detail: str = ""):
        self.state = state
        self.rel = rel
        self.path = path
        self.detail = detail

    @property
    def refused(self) -> bool:
        return self.state in REFUSING

    def __repr__(self) -> str:  # shows up in test failures, so make it say something
        return "Disposition(%s, %s, %s)" % (self.state, self.rel, self.detail)


def _owner_evidence(rel: str) -> str:
    """How mir proves it owns `rel`. Three kinds, because the artifacts differ in kind.

    Anything under `.mir/` is mir's own namespace -- the generated manifest denies writes
    there, so a file in it came from mir by construction. `.claude/settings.json` is SHARED
    with the user, so ownership is only "mir can still read it back"; the merge preserves
    everything else. Every other artifact must carry the ownership marker in its bytes, and
    that is the default on purpose: an artifact added later fails closed until it says who
    wrote it, rather than silently inheriting permission to clobber.
    """
    if rel == ".mir" or rel.startswith(".mir" + os.sep) or rel.startswith(".mir/"):
        return "namespace"
    if rel == os.path.join(".claude", "settings.json") or rel == ".claude/settings.json":
        return "parses"
    return "marker"


def inspect_destination(repo: str, rel: str) -> Disposition:
    """Classify a write target without writing to, or following, anything.

    os.path.exists() is the wrong question and answering it is the bug: it returns False for
    a DANGLING symlink, so a check built on it still follows the link and creates the file it
    points at. Ownership is decided by os.path.lexists / os.path.islink, which describe the
    link itself.
    """
    dest = os.path.join(repo, rel)

    # A symlinked PARENT redirects the write just as effectively as a symlinked file --
    # `.claude -> ~/.claude` sends settings.json into the home config. Walk the components.
    parent = os.path.dirname(dest)
    walked = repo
    for part in os.path.relpath(parent, repo).split(os.sep):
        if part in ("", "."):
            continue
        walked = os.path.join(walked, part)
        if os.path.islink(walked):
            return Disposition(SYMLINK, rel, walked,
                               "parent directory is a symlink to %s" % os.path.realpath(walked))
        if os.path.lexists(walked) and not os.path.isdir(walked):
            return Disposition(NON_REGULAR, rel, walked, "parent path is not a directory")

    if os.path.islink(dest):
        target = os.path.realpath(dest)
        dangling = "" if os.path.exists(dest) else " (dangling)"
        return Disposition(SYMLINK, rel, dest, "symlink%s to %s" % (dangling, target))
    if not os.path.lexists(dest):
        return Disposition(ABSENT, rel, dest)
    if not os.path.isfile(dest):
        return Disposition(NON_REGULAR, rel, dest, "exists but is not a regular file")

    evidence = _owner_evidence(rel)
    if evidence == "namespace":
        return Disposition(MIR_OWNED, rel, dest, "under .mir/, which mir owns outright")
    try:
        with open(dest, encoding="utf-8") as f:
            body = f.read()
    except OSError as e:
        return Disposition(NON_REGULAR, rel, dest, "cannot be read: %s" % e)
    except UnicodeDecodeError as e:
        # Decode strictly, and refuse rather than repair: errors="replace" would let mir
        # write the mangled text back and call it a regeneration.
        return Disposition(UNPARSEABLE if evidence == "parses" else UNOWNED, rel, dest,
                           "is not valid UTF-8: %s" % e)
    if evidence == "parses":
        try:
            json.loads(body)
        except ValueError as e:
            return Disposition(UNPARSEABLE, rel, dest, "not valid JSON: %s" % e)
        return Disposition(MIR_OWNED, rel, dest, "parses, so the merge can preserve it")
    if MARK in body:
        return Disposition(MIR_OWNED, rel, dest, "carries the mir ownership marker")
    return Disposition(UNOWNED, rel, dest, "exists and carries no mir ownership marker")


def _backup(path: str) -> str:
    """Copy a file mir refuses to overwrite to a sidecar, without ever clobbering a backup.

    A backup that overwrites an earlier backup destroys the thing it was made to save, so
    the suffix counts up instead.
    """
    candidate = path + ".mir-backup"
    n = 1
    while os.path.lexists(candidate):
        candidate = "%s.mir-backup.%d" % (path, n)
        n += 1
    shutil.copy2(path, candidate)
    return candidate


def _write_owned(dest: str, content: str) -> None:
    """Write with O_NOFOLLOW so the kernel refuses a symlink even if one appears after the
    inspection -- the check and the write are separate syscalls, and that gap is exploitable.
    """
    flags = os.O_CREAT | os.O_WRONLY | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
    fd = os.open(dest, flags, 0o644)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)


def _pillars(resolved: list[str]) -> list[str]:
    return [s for s in resolved if s.count("-") == 1]


def thin_agents_md(repo_name: str, resolved: list[str], answers: dict, stamp: str) -> str:
    pillars = _pillars(resolved)
    stack_lines = []
    for pillar, choice in answers.items():
        vals = choice if isinstance(choice, list) else [choice]
        stack_lines.append(f"- {pillar}: {', '.join(vals)}")
    lines = [
        f"# {repo_name} — Make It Right baseline",
        "",
        "> AI makes it work. Make It Right. This file only names the disciplines that apply",
        "> here; the depth lives in the `mir-*` skills, which load on demand. Keep it thin —",
        "> never paste skill content into this file (it is billed on every request).",
        "",
        "## The one hard rule",
        "Do not write implementation code until constraints are discovered, assumptions are",
        "confirmed, and the design is approved. On ambiguity, stop and ask.",
        "",
        "## Pillars that apply to this repo",
    ]
    for p in pillars:
        lines.append(f"- `{p}` — loads on a matching task")
    lines += [
        "",
        f"## Stack (chosen via mir init, {stamp})",
        *(stack_lines or ["- (none recorded)"]),
        "",
        "## Write policy",
        "Writes are constrained by `.mir/manifest.json` and enforced by `.mir/guard.py`",
        "(a PreToolUse hook registered in `.claude/settings.json`). Denied: secrets, `.git`,",
        "home config, the policy itself. Run `python3 .mir/probe.py --repo .` to check it.",
        "",
        f"<!-- {MARK}; owned_by_mir. Re-run `mir init` to regenerate ABOVE this line. -->",
        TAIL_LINE,
        "",
    ]
    return "\n".join(lines)


def claude_md() -> str:
    """CLAUDE.md carries the tail marker too, because it is documented as having room for
    repo notes. Without the marker that promise was a lie: the file was rewritten whole.
    """
    return (
        "@AGENTS.md\n\n"
        f"<!-- {MARK}: this imports the thin baseline above. Add repo-specific notes below. -->\n"
        f"{TAIL_LINE}\n"
    )


def _mir_hook_entry(entry, cmd: str) -> bool:
    """Is this PreToolUse entry mir's? By tag first, by command second.

    The tag is how mir re-finds its own entry after the user has edited around it; the
    command match catches an entry written before the tag existed.
    """
    if not isinstance(entry, dict):
        return False
    if entry.get("_mir") == HOOK_TAG:
        return True
    hooks = entry.get("hooks")
    if isinstance(hooks, list):
        for h in hooks:
            if isinstance(h, dict) and h.get("command") == cmd:
                return True
    try:
        return HOOK_TAG in json.dumps(entry)
    except (TypeError, ValueError):
        return False


def merge_settings(existing: dict | None, guard_rel: str) -> tuple[dict, bool]:
    """Reconcile the mir PreToolUse hook to its desired shape. Returns (settings, changed).

    This used to return early the moment it saw the tag, which made the marker a boolean:
    an entry tagged `mir-init-guard` whose matcher had gone stale survived every
    regeneration, and the user gained no coverage while the run reported success. The tag is
    an ADDRESS -- it says WHERE mir's entry is -- so finding it is the start of the work, not
    the end. `changed` is now a real before/after comparison, so re-running on a correct file
    still reports no change.
    """
    settings = copy.deepcopy(existing) if isinstance(existing, dict) else {}
    before = json.dumps(settings, sort_keys=True)
    hooks = settings.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise GenerateError(
            "`.claude/settings.json` has a `hooks` key that is not an object, so mir cannot "
            "merge into it without guessing. Fix or move the file and re-run.")
    pre = hooks.setdefault("PreToolUse", [])
    if not isinstance(pre, list):
        raise GenerateError(
            "`.claude/settings.json` has a `hooks.PreToolUse` that is not a list, so mir "
            "cannot merge into it without guessing. Fix or move the file and re-run.")
    cmd = f'python3 "$CLAUDE_PROJECT_DIR/{guard_rel}"'
    desired = {
        "matcher": MATCHER,
        "_mir": HOOK_TAG,
        "hooks": [{"type": "command", "command": cmd}],
    }
    ours = [i for i, entry in enumerate(pre) if _mir_hook_entry(entry, cmd)]
    if ours:
        pre[ours[0]] = desired
        for i in reversed(ours[1:]):
            del pre[i]      # older runs could append a second entry; collapse to exactly one
    else:
        pre.append(desired)
    return settings, json.dumps(settings, sort_keys=True) != before


def plan(repo: str, resolved: list[str], answers: dict, stamp: str) -> list[dict]:
    """Compute the file writes without performing them. Each item: {path, content, note}."""
    repo_name = os.path.basename(os.path.abspath(repo))
    items: list[dict] = []

    manifest = schema.project_manifest(repo_name, allowed_write_roots=["."])
    manifest["generated_at"] = stamp
    manifest["stack"] = answers
    manifest["skills"] = resolved
    items.append({"path": ".mir/manifest.json",
                  "content": json.dumps(manifest, indent=2) + "\n", "note": "project policy"})

    # All mir-owned files live under .mir/, which is a denied path -- so the agent cannot
    # rewrite the guard, probe, or manifest to widen its own permissions.
    with open(os.path.join(HERE, "guard.py"), encoding="utf-8") as f:
        items.append({"path": ".mir/guard.py", "content": f.read(),
                      "note": "the enforcing hook (copied, self-protected under .mir/)"})
    with open(os.path.join(HERE, "probe.py"), encoding="utf-8") as f:
        items.append({"path": ".mir/probe.py", "content": f.read(),
                      "note": "manifest-derived verifier"})

    # The settings merge reads the destination, so it must inspect it first: a symlinked or
    # unparseable settings.json is NOT "absent". Treating it as absent is how an existing
    # hook set got replaced wholesale. Read it only when the inspection says it is safe.
    settings_rel = os.path.join(".claude", "settings.json")
    settings_disp = inspect_destination(repo, settings_rel)
    existing = None
    if settings_disp.state == MIR_OWNED:
        with open(settings_disp.path, encoding="utf-8") as f:
            existing = json.load(f)
    settings, changed = merge_settings(existing, ".mir/guard.py")
    if changed or settings_disp.refused:
        items.append({"path": ".claude/settings.json",
                      "content": json.dumps(settings, indent=2) + "\n",
                      "note": "PreToolUse hook (merged)" if existing else "PreToolUse hook"})

    items.append({"path": "AGENTS.md",
                  "content": thin_agents_md(repo_name, resolved, answers, stamp),
                  "note": "thin baseline (regenerates above the marker)"})
    items.append({"path": "CLAUDE.md", "content": claude_md(), "note": "imports AGENTS.md"})

    # Classify every destination here, before a caller can write any of them. --dry-run
    # prints these notes and stops, so an unsafe destination is visible without a backup
    # being written; apply() re-inspects and is the one that refuses.
    for it in items:
        d = inspect_destination(repo, it["path"])
        it["disposition"] = d.state
        if d.refused:
            it["note"] = "REFUSED: %s (%s)" % (d.detail, d.state)
    return items


def install_project_skills(repo: str, resolved: list[str], repo_dir: str = None) -> list[str]:
    """Symlink this repo's tiers/modules into <repo>/.claude/skills/.

    Claude Code merges ~/.claude/skills with <repo>/.claude/skills, so with a global
    install of --scope=pillars the repo ends up with exactly: the 7 pillars (everywhere)
    plus the handful of tiers/modules this repo actually uses. A repo that never runs
    mir init still gets the pillar gates, which is the right graceful degradation.

    Depth-1 slugs are skipped: they are the global floor, and personal skills take
    precedence over project skills anyway, so a local copy would be shadowed.

    `repo_dir` defaults to this file's checkout, matching prune_project_skills, so existing
    two-argument call sites keep working unchanged.

    An existing `mir-<slug>` link is only replaced if it resolves inside `repo_dir` --
    the same _owned_by test prune uses. Without it, a name mir itself would resolve is
    enough to overwrite whatever that name points at, which can be a user's own
    `mir-frontend-react` link into a different checkout or their own edited copy. That is
    the same class of bug prune had (finding 9), just narrower: it only touches names mir
    itself would install, where prune's hole could touch any `mir-*` name at all.
    """
    if repo_dir is None:
        repo_dir = os.path.dirname(HERE)
    dest_dir = os.path.join(repo, ".claude", "skills")
    os.makedirs(dest_dir, exist_ok=True)
    linked = []
    for slug in resolved:
        if slug.count("-") <= 1:
            continue                      # pillar: lives in the global floor
        src = os.path.join(repo_dir, "skills", slug)
        if not os.path.isdir(src):
            continue
        dst = os.path.join(dest_dir, slug)
        if os.path.lexists(dst) and not os.path.islink(dst):
            continue                      # never clobber a real directory
        if os.path.islink(dst) and not _owned_by(dst, repo_dir):
            # Points somewhere mir did not put it -- a foreign checkout or a user's own
            # edited copy wearing the same slug name. KEEP, same messaging style as prune.
            print("KEEP %s -- points outside %s, not mir's to replace" %
                  (os.path.relpath(dst, repo), repo_dir))
            continue
        if os.path.islink(dst):
            os.unlink(dst)                # lexists, not exists: a dangling link is still there
        os.symlink(src, dst)
        linked.append(slug)
    return linked


def _owned_by(link: str, base: str) -> bool:
    """Does `link` resolve to something beneath `base`? Ownership is where it POINTS.

    A name starting `mir-` is not proof mir made it: a user's own `mir-private` link, or one
    from a second checkout, wears the same prefix. realpath resolves the chain, so a link
    laundered through an intermediate link is still judged by its final target.
    """
    target = os.path.realpath(link)
    root = os.path.realpath(base)
    return target == root or target.startswith(root + os.sep)


def prune_project_skills(repo: str, keep: list[str], repo_dir: str = None) -> list[str]:
    """Remove mir-* symlinks in <repo>/.claude/skills that are no longer resolved.

    Without this, re-running mir init after a stack change leaves the old stack's skills
    loading forever -- the exact context creep this feature exists to remove.

    `repo_dir` is the mir checkout whose links may be pruned; it defaults to this file's
    checkout so existing callers keep working unchanged. Only links resolving beneath it are
    removed: deleting a link mir did not create is data loss with a tidy-up excuse.
    """
    if repo_dir is None:
        repo_dir = os.path.dirname(HERE)
    dest_dir = os.path.join(repo, ".claude", "skills")
    if not os.path.isdir(dest_dir):
        return []
    keep_set = set(keep)
    removed = []
    for name in sorted(os.listdir(dest_dir)):
        if not name.startswith("mir-") or name in keep_set:
            continue
        p = os.path.join(dest_dir, name)
        if not os.path.islink(p):
            continue                      # a real directory is a human's work, never ours
        if not _owned_by(p, repo_dir):
            continue                      # points outside this checkout: not mir's to delete
        os.unlink(p)
        removed.append(name)
    return removed


# -- settings.local.json: inspected, never written -------------------------------------
#
# Claude Code merges .claude/settings.json AND .claude/settings.local.json, and either can
# carry a PreToolUse hook (probe.py's wiring phase already reads both -- see
# find_wiring_entries there). mir only MERGES settings.json: settings.local.json is
# conventionally gitignored and per-developer, so mir writing into it would put a shared
# tool's hand in a file the checked-in repo never sees and the user did not ask mir to
# manage. That argues for leaving it alone entirely.
#
# But a stale mir-tagged entry sitting there is not a neutral fact: the user believes a
# hook is armed, the probe may even call it "wired" because the tag or the guard.py command
# is present, and the matcher underneath has drifted so the guard never actually fires.
# Silence there is worse than the merge silence would be, because it reads as protected and
# is not. So mir inspects this file read-only -- it is not a write target, so it never goes
# through inspect_destination/apply() -- and hands back findings for the CLI layer to print.
# This function performs no I/O beyond a read and never raises for a file mir does not own:
# an unreadable or unparseable settings.local.json is reported as "could not check", not a
# GenerateError, because refusing the whole run over a file mir was never going to touch
# would be a bigger overreach than the silent-drift it exists to catch.
LOCAL_SETTINGS_REL = os.path.join(".claude", "settings.local.json")


def local_settings_warnings(repo: str, guard_rel: str = ".mir/guard.py") -> list[str]:
    """Human-readable warnings about a stale mir-tagged PreToolUse hook in
    `.claude/settings.local.json`. Empty when there is nothing to report: the file is
    absent, unreadable/unparseable (best-effort only -- mir does not own this file), has no
    `hooks.PreToolUse` list, or every mir-tagged entry already matches the desired shape.

    Callers are expected to print these loudly and otherwise leave the file untouched --
    this function never writes anything and is not part of plan()/apply().
    """
    path = os.path.join(repo, LOCAL_SETTINGS_REL)
    if os.path.islink(path) or not os.path.isfile(path):
        return []  # absent, or a link mir will not follow to inspect
    try:
        with open(path, encoding="utf-8") as f:
            settings = json.load(f)
    except (OSError, UnicodeDecodeError, ValueError) as e:
        return ["%s could not be read as JSON (%s), so mir could not check it for a stale "
                "mir-tagged hook. mir does not own this file and will not fix it for you."
                % (LOCAL_SETTINGS_REL, e)]
    if not isinstance(settings, dict):
        return []
    hooks = settings.get("hooks")
    pre = hooks.get("PreToolUse") if isinstance(hooks, dict) else None
    if not isinstance(pre, list):
        return []

    cmd = f'python3 "$CLAUDE_PROJECT_DIR/{guard_rel}"'
    findings = []
    for entry in pre:
        if not isinstance(entry, dict) or not _mir_hook_entry(entry, cmd):
            continue
        matcher = entry.get("matcher")
        entry_hooks = entry.get("hooks") if isinstance(entry.get("hooks"), list) else []
        cmds = [h.get("command") for h in entry_hooks if isinstance(h, dict)]
        if matcher == MATCHER and cmd in cmds:
            continue  # this entry is exactly the desired shape: nothing to report
        findings.append(
            "%s has a mir-tagged PreToolUse hook that is STALE: matcher=%r, command(s)=%r "
            "-- does not match the desired matcher %r / command %r. mir will not rewrite "
            "this file (it is conventionally gitignored and per-developer); fix the entry "
            "by hand, or delete it and re-run `mir init` so the guard actually fires."
            % (LOCAL_SETTINGS_REL, matcher, cmds, MATCHER, cmd))
    return findings


def _preserve_tail(dest: str, disposition: str, new_content: str) -> str:
    """Keep whatever the human wrote below the tail marker, in EVERY artifact that has one.

    This used to be hard-coded to `rel != "AGENTS.md"`, so CLAUDE.md carried an ownership
    marker that meant nothing -- the file was rewritten whole despite being documented as
    having room for repo notes. The rule is now derived from the content mir is about to
    write: an artifact that emits the tail marker gets tail preservation, which is what makes
    a sixth artifact covered the day it is added rather than the day someone remembers.
    """
    if TAIL_MARK not in new_content:
        return new_content
    if disposition != MIR_OWNED:
        return new_content              # absent, or refused; there is no tail to keep
    with open(dest, encoding="utf-8") as f:
        old = f.read()
    if TAIL_MARK not in old:
        return new_content
    tail = old.split(TAIL_MARK, 1)[1]
    return new_content + tail.lstrip("\n")


def _refusal_report(refusals: list) -> str:
    lines = ["refusing to write %d destination(s) mir does not own:" % len(refusals)]
    for d, backup in refusals:
        lines.append("  %s -- %s" % (d.rel, d.detail))
        if backup:
            lines.append("      a copy was saved to %s" % backup)
    lines.append("Move or remove the file(s), or point mir at a different repo, and re-run.")
    return "\n".join(lines)


def apply(repo: str, items: list[dict]) -> list[str]:
    """Write the plan, or write none of it.

    Every destination is inspected before the first byte lands, because a run that aborts
    halfway leaves a harness that looks installed and enforces nothing -- worse than no
    harness at all, which at least tells the truth.
    """
    dispositions = {}
    refused = []
    for it in items:
        d = inspect_destination(repo, it["path"])
        dispositions[it["path"]] = d
        if d.refused:
            refused.append(d)
    if refused:
        # Back up only now, and only the regular files whose content is at stake: a symlink
        # or a device node is refused precisely because reading it is the hazard.
        pairs = [(d, _backup(d.path) if d.state in BACKED_UP else "") for d in refused]
        raise GenerateError(_refusal_report(pairs))

    written = []
    for it in items:
        dest = os.path.join(repo, it["path"])
        parent = os.path.dirname(dest)
        if parent:
            os.makedirs(parent, exist_ok=True)
        content = _preserve_tail(dest, dispositions[it["path"]].state, it["content"])
        _write_owned(dest, content)
        written.append(it["path"])
    return written
