"""Emit the per-project artifacts: manifest, guard, hooks, thin AGENTS.md, CLAUDE.md, COVERAGE.

This file no longer knows what a Claude Code settings file looks like. Each host lives in
init/targets/ and hands back `{path, content, note}` items; the generator's job is the part
that is the same for all of them -- classify every destination before a byte lands, write all
of it or none of it, and preserve the human's tail. `merge_settings` moved to
targets/claude.py, where Claude Code's config schema belongs, and is re-exported here so
existing callers keep working.

Design rules that came straight out of the plan reviews:
  - AGENTS.md stays THIN (EXTENDING.md Rule 2): it names the pillars that apply and the one
    hard rule, and defers all depth to the skills. It never inlines skill content.
  - .claude/settings.json is MERGED, not overwritten: an existing hook set is preserved and
    the mir hook is reconciled to the desired shape, so re-running is idempotent.
  - Every generated file carries an ownership marker so a human and a re-run both know mir
    owns it. Content below the marker is preserved on regeneration, in EVERY artifact that
    offers a tail -- the marker is an address, not a flag.
  - Nothing is written to a destination that has not been inspected first. Every write
    target is classified (absent / mir-owned / unowned / symlink / non-regular /
    unparseable) BEFORE the first byte lands, and a destination mir does not own aborts the
    whole run. A partial harness is worse than none, because it looks installed.
  - --dry-run prints the diff of what would change and writes nothing -- including no
    backups, which is why refusal is decided in plan() and executed in apply().
"""

from __future__ import annotations

import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)
import agents_export  # noqa: E402
import schema  # noqa: E402
import targets as targets_pkg  # noqa: E402
from targets.base import GenerateError  # noqa: E402,F401  (re-exported; see below)
from targets.claude import (HOOK_TAG, MATCHER, _mir_hook_entry,  # noqa: E402,F401
                            guard_command as claude_guard_command, merge_settings)

# GenerateError, HOOK_TAG, MATCHER and merge_settings are RE-EXPORTED rather than
# re-defined. GenerateError in particular has to be the same class object the targets raise,
# or cli.py's `except gen.GenerateError` would let a refusal raised inside targets/claude.py
# escape as an unhandled traceback -- two classes with one name is the worst possible way to
# discover that a destination was refused.

MARK = "generated by mir init"

# The end of the mir-owned region in any text artifact. Everything after it belongs to the
# human and survives regeneration. It is a single constant rather than a per-file rule so
# that a new artifact gets tail preservation by emitting the line, not by editing a list.
TAIL_MARK = "preserved across regenerations. -->"
TAIL_LINE = "<!-- Anything you write BELOW this line is preserved across regenerations. -->"


# -- destination safety -----------------------------------------------------------------
# apply() used to be makedirs + open(dest, "w"), which cannot tell an absent file from a
# symlink into $HOME, so it truncated whatever the link pointed at. Every destination is
# now classified first, and the classification -- not the filename -- decides the write.

ABSENT = "absent"              # nothing there: write it
MIR_OWNED = "mir_owned"        # a file mir wrote: rewrite it
UNOWNED = "unowned"            # a real file with no mir ownership evidence: refuse
SYMLINK = "symlink"            # a link (live OR dangling): refuse, never follow
NON_REGULAR = "non_regular"    # directory, fifo, device, unreadable: refuse
UNPARSEABLE = "unparseable"    # a merge target mir cannot read back: refuse

# Refusing on UNPARSEABLE is the point of finding 6: a settings.json that will not parse was
# treated as absent, so every hook the user had was silently replaced by mir's one hook.
REFUSING = (UNOWNED, SYMLINK, NON_REGULAR, UNPARSEABLE)

# Only a regular file whose bytes we are refusing to overwrite gets copied aside. A symlink
# or a device node is NOT backed up: reading it is the exact hazard the refusal exists for.
BACKED_UP = (UNOWNED, UNPARSEABLE)


class Disposition:
    """What is at a destination, and therefore what mir is allowed to do with it."""

    def __init__(self, state: str, rel: str, path: str, detail: str = ""):
        self.state = state
        self.rel = rel
        self.path = path
        self.detail = detail

    @property
    def refused(self) -> bool:
        return self.state in REFUSING

    def __repr__(self) -> str:  # shows up in test failures, so make it say something
        return "Disposition(%s, %s, %s)" % (self.state, self.rel, self.detail)


def _owner_evidence(rel: str) -> str:
    """How mir proves it owns `rel`. Three kinds, because the artifacts differ in kind.

    Anything under `.mir/` is mir's own namespace -- the generated manifest denies writes
    there, so a file in it came from mir by construction. `.claude/settings.json` is SHARED
    with the user, so ownership is only "mir can still read it back"; the merge preserves
    everything else. Every other artifact must carry the ownership marker in its bytes, and
    that is the default on purpose: an artifact added later fails closed until it says who
    wrote it, rather than silently inheriting permission to clobber.
    """
    if rel == ".mir" or rel.startswith(".mir" + os.sep) or rel.startswith(".mir/"):
        return "namespace"
    if rel == os.path.join(".claude", "settings.json") or rel == ".claude/settings.json":
        return "parses"
    return "marker"


def inspect_destination(repo: str, rel: str) -> Disposition:
    """Classify a write target without writing to, or following, anything.

    os.path.exists() is the wrong question and answering it is the bug: it returns False for
    a DANGLING symlink, so a check built on it still follows the link and creates the file it
    points at. Ownership is decided by os.path.lexists / os.path.islink, which describe the
    link itself.
    """
    dest = os.path.join(repo, rel)

    # A symlinked PARENT redirects the write just as effectively as a symlinked file --
    # `.claude -> ~/.claude` sends settings.json into the home config. Walk the components.
    parent = os.path.dirname(dest)
    walked = repo
    for part in os.path.relpath(parent, repo).split(os.sep):
        if part in ("", "."):
            continue
        walked = os.path.join(walked, part)
        if os.path.islink(walked):
            return Disposition(SYMLINK, rel, walked,
                               "parent directory is a symlink to %s" % os.path.realpath(walked))
        if os.path.lexists(walked) and not os.path.isdir(walked):
            return Disposition(NON_REGULAR, rel, walked, "parent path is not a directory")

    if os.path.islink(dest):
        target = os.path.realpath(dest)
        dangling = "" if os.path.exists(dest) else " (dangling)"
        return Disposition(SYMLINK, rel, dest, "symlink%s to %s" % (dangling, target))
    if not os.path.lexists(dest):
        return Disposition(ABSENT, rel, dest)
    if not os.path.isfile(dest):
        return Disposition(NON_REGULAR, rel, dest, "exists but is not a regular file")

    evidence = _owner_evidence(rel)
    if evidence == "namespace":
        return Disposition(MIR_OWNED, rel, dest, "under .mir/, which mir owns outright")
    try:
        with open(dest, encoding="utf-8") as f:
            body = f.read()
    except OSError as e:
        return Disposition(NON_REGULAR, rel, dest, "cannot be read: %s" % e)
    except UnicodeDecodeError as e:
        # Decode strictly, and refuse rather than repair: errors="replace" would let mir
        # write the mangled text back and call it a regeneration.
        return Disposition(UNPARSEABLE if evidence == "parses" else UNOWNED, rel, dest,
                           "is not valid UTF-8: %s" % e)
    if evidence == "parses":
        try:
            json.loads(body)
        except ValueError as e:
            return Disposition(UNPARSEABLE, rel, dest, "not valid JSON: %s" % e)
        return Disposition(MIR_OWNED, rel, dest, "parses, so the merge can preserve it")
    if MARK in body:
        return Disposition(MIR_OWNED, rel, dest, "carries the mir ownership marker")
    return Disposition(UNOWNED, rel, dest, "exists and carries no mir ownership marker")


def _backup(path: str) -> str:
    """Copy a file mir refuses to overwrite to a sidecar, without ever clobbering a backup.

    A backup that overwrites an earlier backup destroys the thing it was made to save, so
    the suffix counts up instead.
    """
    candidate = path + ".mir-backup"
    n = 1
    while os.path.lexists(candidate):
        candidate = "%s.mir-backup.%d" % (path, n)
        n += 1
    shutil.copy2(path, candidate)
    return candidate


def _write_owned(dest: str, content: str) -> None:
    """Write with O_NOFOLLOW so the kernel refuses a symlink even if one appears after the
    inspection -- the check and the write are separate syscalls, and that gap is exploitable.
    """
    flags = os.O_CREAT | os.O_WRONLY | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
    fd = os.open(dest, flags, 0o644)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)


def _pillars(resolved: list[str]) -> list[str]:
    return [s for s in resolved if s.count("-") == 1]


# The tightest per-rule-file limit of the three hosts that read root AGENTS.md. Antigravity
# caps a rule file at 12,000 characters -- tighter than the 32 KiB Codex figure EXTENDING.md
# cites -- so this is the number the file is tested against. A file over the cap is not
# rejected loudly; it is TRUNCATED, and a truncated write-policy paragraph is a harness that
# documents a rule the agent never reads.
AGENTS_MD_CAP = 12000


def _write_policy_lines(targets) -> list:
    """The write-policy paragraph, naming the targets that enforce and the ones that do not.

    This paragraph used to say, unconditionally, that writes are "enforced by `.mir/guard.py`
    (a PreToolUse hook registered in `.claude/settings.json`)". That became false the moment
    anyone ran `--target codex`: the hook is in `.codex/hooks.json`, and for `--target cursor`
    there is no hook at all. A generated file that overstates its own enforcement is the
    defect class this release closes, reproduced in the artifact the agent reads on every
    request.

    So the levels are read off the targets themselves, and an advisory target is named IN THE
    SAME BREATH as the enforcing ones rather than in a footnote further down -- an agent that
    stops reading after the first sentence must not stop reading after the reassuring half.
    """
    groups = targets_pkg.enforcement_groups(targets)
    enforced = groups.get("enforced", [])
    unverified = groups.get("unverified", [])
    advisory = groups.get("advisory", []) + groups.get("none", [])

    lines = ["Writes are constrained by `.mir/manifest.json`."]
    if enforced:
        lines.append("ENFORCED for %s: `.mir/guard.py` runs as a pre-tool hook and blocks."
                     % ", ".join(enforced))
    if unverified:
        lines.append("UNVERIFIED for %s: a hook file was written, but nobody has proven the "
                     "host invokes it." % ", ".join(unverified))
    if advisory:
        lines.append("NOT ENFORCED for %s -- the policy is advisory there and nothing stops a "
                     "write." % ", ".join(advisory))
    if not enforced:
        lines.append("No target here enforces anything. Treat every rule below as advisory.")
    lines.append("Denied: secrets, `.git`, home config, the policy itself.")
    lines.append("Per-target detail, and what was NOT proven, is in `.mir/COVERAGE.md` --")
    lines.append("this file stays thin, so no hook JSON or per-tool config lives here.")
    lines.append("Run `python3 .mir/probe.py --repo .` to check it.")
    return lines


def thin_agents_md(repo_name: str, resolved: list[str], answers: dict, stamp: str,
                   targets=None) -> str:
    targets = list(targets) if targets else [targets_pkg.BY_NAME[targets_pkg.DEFAULT]]
    pillars = _pillars(resolved)
    stack_lines = []
    for pillar, choice in answers.items():
        vals = choice if isinstance(choice, list) else [choice]
        stack_lines.append(f"- {pillar}: {', '.join(vals)}")
    lines = [
        f"# {repo_name} — Make It Right baseline",
        "",
        "> AI makes it work. Make It Right. This file only names the disciplines that apply",
        "> here; the depth lives in the `mir-*` skills, which load on demand. Keep it thin —",
        "> never paste skill content into this file (it is billed on every request).",
        "",
        "## The one hard rule",
        "Do not write implementation code until constraints are discovered, assumptions are",
        "confirmed, and the design is approved. On ambiguity, stop and ask.",
        "",
        "## Pillars that apply to this repo",
    ]
    for p in pillars:
        lines.append(f"- `{p}` — loads on a matching task")
    lines += [
        "",
        f"## Stack (chosen via mir init, {stamp})",
        *(stack_lines or ["- (none recorded)"]),
        "",
        f"## Targets (chosen via mir init, {stamp})",
        "- " + ", ".join(t.name for t in targets),
        "",
        "## Write policy",
        *_write_policy_lines(targets),
        "",
        f"<!-- {MARK}; owned_by_mir. Re-run `mir init` to regenerate ABOVE this line. -->",
        TAIL_LINE,
        "",
    ]
    return "\n".join(lines)


def claude_md() -> str:
    """CLAUDE.md carries the tail marker too, because it is documented as having room for
    repo notes. Without the marker that promise was a lie: the file was rewritten whole.
    """
    return (
        "@AGENTS.md\n\n"
        f"<!-- {MARK}: this imports the thin baseline above. Add repo-specific notes below. -->\n"
        f"{TAIL_LINE}\n"
    )


def _read_owned_json(repo: str):
    """A reader a target may safely call: parsed JSON, or None.

    Injected into the target Context rather than handed out as a filesystem path, because
    deciding whether a destination is safe to read back is THIS layer's job. A symlinked or
    unparseable settings.json is not "absent", and treating it as absent is how an existing
    hook set got replaced wholesale. A target that opened the file itself would bypass every
    check inspect_destination exists to perform.
    """
    def read(rel):
        disp = inspect_destination(repo, rel)
        if disp.state != MIR_OWNED:
            return None
        try:
            with open(disp.path, encoding="utf-8") as f:
                return json.load(f)
        except (OSError, ValueError, UnicodeDecodeError):
            return None
    return read


def plan(repo: str, resolved: list[str], answers: dict, stamp: str, targets=None) -> list[dict]:
    """Compute the file writes without performing them. Each item: {path, content, note}.

    `targets` defaults to Claude Code alone, which is what every v1 caller meant and what a
    bare `mir init` still means. The default is spelled once, here, rather than in each
    caller: a second spelling of it is a second place for the implicit target to drift.
    """
    targets = list(targets) if targets else [targets_pkg.BY_NAME[targets_pkg.DEFAULT]]
    repo_name = os.path.basename(os.path.abspath(repo))
    items: list[dict] = []

    manifest = schema.project_manifest(
        repo_name, allowed_write_roots=["."],
        targets=targets_pkg.manifest_block(targets))
    manifest["generated_at"] = stamp
    manifest["stack"] = answers
    manifest["skills"] = resolved
    items.append({"path": ".mir/manifest.json",
                  "content": json.dumps(manifest, indent=2) + "\n", "note": "project policy"})

    # All mir-owned files live under .mir/, which is a denied path -- so the agent cannot
    # rewrite the guard, probe, or manifest to widen its own permissions.
    with open(os.path.join(HERE, "guard.py"), encoding="utf-8") as f:
        items.append({"path": ".mir/guard.py", "content": f.read(),
                      "note": "the enforcing hook (copied, self-protected under .mir/)"})
    with open(os.path.join(HERE, "probe.py"), encoding="utf-8") as f:
        items.append({"path": ".mir/probe.py", "content": f.read(),
                      "note": "manifest-derived verifier"})

    ctx = targets_pkg.Context(
        repo=repo, repo_name=repo_name, resolved=resolved, answers=answers, stamp=stamp,
        guard_rel=".mir/guard.py", target_names=[t.name for t in targets],
        read_owned_json=_read_owned_json(repo))

    for target in targets:
        for it in target.plan_items(ctx):
            # `changed=False` means the destination already holds exactly this content. It is
            # still emitted when the destination is REFUSED, because a refusal has to be
            # reported even when the bytes mir would write are identical -- silence there
            # would read as "nothing to do" rather than "mir will not touch that file".
            if it.pop("changed", True) or inspect_destination(repo, it["path"]).refused:
                items.append(it)

    items.append({"path": "AGENTS.md",
                  "content": thin_agents_md(repo_name, resolved, answers, stamp, targets),
                  "note": "thin baseline (regenerates above the marker)"})
    items.append({"path": "CLAUDE.md", "content": claude_md(), "note": "imports AGENTS.md"})
    items.append({"path": ".mir/COVERAGE.md",
                  "content": coverage_md(repo_name, targets, stamp),
                  "note": "what each target does and does NOT prove"})

    # Classify every destination here, before a caller can write any of them. --dry-run
    # prints these notes and stops, so an unsafe destination is visible without a backup
    # being written; apply() re-inspects and is the one that refuses.
    for it in items:
        d = inspect_destination(repo, it["path"])
        it["disposition"] = d.state
        if d.refused:
            it["note"] = "REFUSED: %s (%s)" % (d.detail, d.state)
    return items


# -- COVERAGE.md: the honesty artifact ---------------------------------------------------
#
# It opens with a VERDICT BLOCK rather than a table, and the ordering is the argument. A
# table invites the reader to find their own row and stop; three lines at the top say what
# is enforced, what is merely emitted, and what is not enforced at all, before anyone can
# skip to the cell they were hoping for. The per-capability rows follow, and every one of
# them carries a "what the probe did NOT prove" cell -- because for an `unverified` target
# that cell is the whole finding, and a row without it reads as coverage.

_VERDICT_LABEL = {
    "enforced": "ENFORCED   (guard decides, host hook registered)",
    "unverified": "UNVERIFIED (hook file emitted, host invocation not proven)",
    "advisory": "ADVISORY ONLY — the manifest is NOT enforced for",
    "none": "NO SURFACE — the host has nothing to enforce with",
}

# Read in the order the reader needs them: the strongest claim first, so the weakest is what
# they are left holding.
_VERDICT_ORDER = ("enforced", "unverified", "advisory", "none")

# The manual command that would settle each target's write-policy claim. Named per target,
# because "test it yourself" is not a procedure. GOAL.md B1.10 carries the long form.
_MANUAL_CHECK = {
    "claude": "restart Claude Code, ask it to write `.git/config`, and confirm the tool call "
              "is blocked with the guard's reason",
    "codex": "run `codex` in this repo, attempt a write to `.git/config`, and record BOTH "
             "whether it was blocked and whether a per-hook trust prompt appeared first",
    "antigravity": "3-phase check: (1) make the hook write a marker file and confirm it fires "
                   "on a file write; (2) attempt a write to `.git/config` and confirm the deny "
                   "is honoured; (3) break the hook command deliberately and confirm the host "
                   "fails OPEN, which is what makes the adapter's fail-closed design load-bearing",
    "cursor": "toggle 'Include third-party Plugins, Skills, and other configs' OFF, attempt a "
              "denied write and record that it succeeds; toggle it ON and record whether the "
              "same write is blocked",
}


def coverage_md(repo_name: str, targets, stamp: str) -> str:
    groups = targets_pkg.enforcement_groups(targets)
    lines = [
        f"# {repo_name} — mir target coverage",
        "",
        f"<!-- {MARK}; owned_by_mir. Generated {stamp}. Re-run `mir init` to regenerate. -->",
        "",
        "What this harness actually enforces, per target, and — for every target it does not",
        "enforce — what specifically was not proven. A green `mir init` run proves the guard",
        "decides correctly and that a registration file exists. It cannot prove a host read it.",
        "",
        "```",
    ]
    for level in _VERDICT_ORDER:
        names = groups.get(level)
        if names:
            lines.append("%s: %s" % (_VERDICT_LABEL[level], ", ".join(sorted(names))))
    lines += ["```", ""]

    lines += [
        "## Per target × capability",
        "",
        "| target | capability | level | mechanism | file emitted | probe proved | probe did NOT prove | confirm by hand |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for t in targets:
        files = ", ".join("`%s`" % f for f in t.wiring_files) or "(none by design)"
        for key in targets_pkg.CAPABILITY_KEYS:
            cap = t.capability(key)           # KeyError here is the B1.1 test, not a bug
            emitted = files if key == "write_policy_enforcement" else "—"
            lines.append("| %s | %s | **%s** | %s | %s | %s | %s | %s |" % (
                t.name, key, cap.level, _cell(cap.mechanism), emitted,
                _cell(_proved(t, key)), _cell(_not_proved(t, key, cap)),
                _cell(_MANUAL_CHECK.get(t.name, "—") if key == "write_policy_enforcement"
                      else "—")))
    lines += ["", "Sources for every claim above:", ""]
    for t in targets:
        for key in targets_pkg.CAPABILITY_KEYS:
            lines.append("- %s / %s — %s" % (t.name, key, t.capability(key).source))

    lines += ["", "## Sub-agent export", "",
              "`agents/*.md` frontmatter is the single source of truth; nothing here is a",
              "checked-in parallel catalog. What could not be carried across, and what it cost:",
              ""]
    for t in targets:
        notes = agents_export.notes(t.name)
        lines.append("**%s**" % t.name)
        for n in notes or ["(nothing recorded)"]:
            lines.append("- %s" % n)
        lines.append("")

    lines += [
        "## What no command in this repository can check",
        "",
        "Listed so a green CI run is not read as covering them. Until each is run by a human,",
        "the target's `write_policy_enforcement` level stays `unverified` and this file says so.",
        "`python3 .mir/probe.py --repo .` verifies the guard and the registration; it does not",
        "verify the host.",
        "",
    ]
    for t in targets:
        if t.capability("write_policy_enforcement").level != "enforced":
            lines.append("- **%s** — %s" % (t.name, _MANUAL_CHECK.get(t.name, "no procedure recorded")))
    lines.append("")
    return "\n".join(lines)


def _cell(text: str) -> str:
    """One markdown table cell. A `|` inside a cell splits the row, and a newline ends the
    table entirely -- a mechanism string that broke the table would take every row below it
    with it."""
    return " ".join(str(text or "—").split()).replace("|", "\\|")


def _proved(target, key: str) -> str:
    if key != "write_policy_enforcement":
        return "nothing — this row is a statement about the host, not a probe result"
    if not target.wiring_files:
        return "nothing. This target registers no file, so there is nothing to verify"
    return ("the guard decides this manifest correctly on %s's verdict channel, and a "
            "registration file exists naming the guard with `--protocol %s`"
            % (target.name, target.guard_protocol))


def _not_proved(target, key: str, cap) -> str:
    """The cell that must never be empty for an `unverified` target.

    It is built from the target's own declared caveats rather than written here, so a caveat
    added to a target file appears in this column on the next run instead of on the day
    someone remembers to update a renderer.
    """
    parts = list(cap.caveats)
    if cap.level == "unverified" and not parts:
        parts = ["level is `unverified` and no caveat was recorded, which is itself the "
                 "finding: state what was not proven"]
    return "; ".join(parts) or "—"


# Where each target reads PROJECT-LOCAL skills from, relative to the repo. `.agents/skills`
# is Antigravity's; Codex and Cursor have no project-local skill directory mir can write to,
# so they contribute none rather than being given a guessed path.
#
# PRUNE matters more than INSTALL here. Without a prune that covers every directory install
# writes to, a repo that switches stacks accumulates the dead stack's skills in
# `.agents/skills` forever -- loading gates for a framework it no longer uses, which is the
# exact context creep this feature exists to remove, one directory over from where it was
# fixed.
TARGET_SKILL_DIRS = {
    "claude": (os.path.join(".claude", "skills"),),
    "antigravity": (os.path.join(".agents", "skills"),),
    "codex": (),
    "cursor": (),
}

DEFAULT_SKILL_DIRS = (os.path.join(".claude", "skills"),)


def skill_dirs_for(targets) -> list:
    """The project-local skill directories to install into and prune, for a target list.

    Deduplicated and ordered, so a target added twice does not link twice, and so the
    reported order is stable enough to assert on.
    """
    out, seen = [], set()
    for t in targets or []:
        name = getattr(t, "name", t)
        for d in TARGET_SKILL_DIRS.get(name, ()):
            if d not in seen:
                seen.add(d)
                out.append(d)
    return out or list(DEFAULT_SKILL_DIRS)


def install_project_skills(repo: str, resolved: list[str], repo_dir: str = None,
                           dest_dirs=None) -> list[str]:
    """Symlink this repo's tiers/modules into every target's project skill directory.

    Claude Code merges ~/.claude/skills with <repo>/.claude/skills, so with a global
    install of --scope=pillars the repo ends up with exactly: the 7 pillars (everywhere)
    plus the handful of tiers/modules this repo actually uses. A repo that never runs
    mir init still gets the pillar gates, which is the right graceful degradation.

    Depth-1 slugs are skipped: they are the global floor, and personal skills take
    precedence over project skills anyway, so a local copy would be shadowed.

    `repo_dir` defaults to this file's checkout, matching prune_project_skills, so existing
    two-argument call sites keep working unchanged. `dest_dirs` likewise defaults to
    `.claude/skills` alone -- a caller that predates cross-agent init gets exactly the
    behaviour it had.

    An existing `mir-<slug>` link is only replaced if it resolves inside `repo_dir` --
    the same _owned_by test prune uses. Without it, a name mir itself would resolve is
    enough to overwrite whatever that name points at, which can be a user's own
    `mir-frontend-react` link into a different checkout or their own edited copy. That is
    the same class of bug prune had (finding 9), just narrower: it only touches names mir
    itself would install, where prune's hole could touch any `mir-*` name at all.

    The return value is a list of SLUGS, deduplicated across directories: linking one skill
    into two hosts is one skill made available, not two, and a caller printing "linked 12"
    for 6 skills would be reporting the implementation instead of the effect.
    """
    if repo_dir is None:
        repo_dir = os.path.dirname(HERE)
    linked, seen = [], set()
    for rel_dir in (dest_dirs if dest_dirs is not None else DEFAULT_SKILL_DIRS):
        dest_dir = os.path.join(repo, rel_dir)
        os.makedirs(dest_dir, exist_ok=True)
        for slug in resolved:
            if slug.count("-") <= 1:
                continue                      # pillar: lives in the global floor
            src = os.path.join(repo_dir, "skills", slug)
            if not os.path.isdir(src):
                continue
            dst = os.path.join(dest_dir, slug)
            if os.path.lexists(dst) and not os.path.islink(dst):
                continue                      # never clobber a real directory
            if os.path.islink(dst) and not _owned_by(dst, repo_dir):
                # Points somewhere mir did not put it -- a foreign checkout or a user's own
                # edited copy wearing the same slug name. KEEP, same messaging as prune.
                print("KEEP %s -- points outside %s, not mir's to replace" %
                      (os.path.relpath(dst, repo), repo_dir))
                continue
            if os.path.islink(dst):
                os.unlink(dst)            # lexists, not exists: a dangling link is still there
            os.symlink(src, dst)
            if slug not in seen:
                seen.add(slug)
                linked.append(slug)
    return linked


def _owned_by(link: str, base: str) -> bool:
    """Does `link` resolve to something beneath `base`? Ownership is where it POINTS.

    A name starting `mir-` is not proof mir made it: a user's own `mir-private` link, or one
    from a second checkout, wears the same prefix. realpath resolves the chain, so a link
    laundered through an intermediate link is still judged by its final target.
    """
    target = os.path.realpath(link)
    root = os.path.realpath(base)
    return target == root or target.startswith(root + os.sep)


def prune_project_skills(repo: str, keep: list[str], repo_dir: str = None,
                         dest_dirs=None) -> list[str]:
    """Remove mir-* symlinks that are no longer resolved, in every target's skill directory.

    Without this, re-running mir init after a stack change leaves the old stack's skills
    loading forever -- the exact context creep this feature exists to remove. `dest_dirs` is
    why it must cover more than `.claude/skills` now: install writes into `.agents/skills`
    too, and a prune that does not follow it leaves a repo accumulating a dead stack's gates
    in a directory nobody thinks to look in.

    `repo_dir` is the mir checkout whose links may be pruned; it defaults to this file's
    checkout so existing callers keep working unchanged. Only links resolving beneath it are
    removed: deleting a link mir did not create is data loss with a tidy-up excuse.
    """
    if repo_dir is None:
        repo_dir = os.path.dirname(HERE)
    keep_set = set(keep)
    removed, seen = [], set()
    for rel_dir in (dest_dirs if dest_dirs is not None else DEFAULT_SKILL_DIRS):
        dest_dir = os.path.join(repo, rel_dir)
        if not os.path.isdir(dest_dir):
            continue
        for name in sorted(os.listdir(dest_dir)):
            if not name.startswith("mir-") or name in keep_set:
                continue
            p = os.path.join(dest_dir, name)
            if not os.path.islink(p):
                continue                  # a real directory is a human's work, never ours
            if not _owned_by(p, repo_dir):
                continue                  # points outside this checkout: not mir's to delete
            os.unlink(p)
            if name not in seen:
                seen.add(name)
                removed.append(name)
    return removed


# -- settings.local.json: inspected, never written -------------------------------------
#
# Claude Code merges .claude/settings.json AND .claude/settings.local.json, and either can
# carry a PreToolUse hook (probe.py's wiring phase already reads both -- see
# find_wiring_entries there). mir only MERGES settings.json: settings.local.json is
# conventionally gitignored and per-developer, so mir writing into it would put a shared
# tool's hand in a file the checked-in repo never sees and the user did not ask mir to
# manage. That argues for leaving it alone entirely.
#
# But a stale mir-tagged entry sitting there is not a neutral fact: the user believes a
# hook is armed, the probe may even call it "wired" because the tag or the guard.py command
# is present, and the matcher underneath has drifted so the guard never actually fires.
# Silence there is worse than the merge silence would be, because it reads as protected and
# is not. So mir inspects this file read-only -- it is not a write target, so it never goes
# through inspect_destination/apply() -- and hands back findings for the CLI layer to print.
# This function performs no I/O beyond a read and never raises for a file mir does not own:
# an unreadable or unparseable settings.local.json is reported as "could not check", not a
# GenerateError, because refusing the whole run over a file mir was never going to touch
# would be a bigger overreach than the silent-drift it exists to catch.
LOCAL_SETTINGS_REL = os.path.join(".claude", "settings.local.json")


def local_settings_warnings(repo: str, guard_rel: str = ".mir/guard.py") -> list[str]:
    """Human-readable warnings about a stale mir-tagged PreToolUse hook in
    `.claude/settings.local.json`. Empty when there is nothing to report: the file is
    absent, unreadable/unparseable (best-effort only -- mir does not own this file), has no
    `hooks.PreToolUse` list, or every mir-tagged entry already matches the desired shape.

    Callers are expected to print these loudly and otherwise leave the file untouched --
    this function never writes anything and is not part of plan()/apply().
    """
    path = os.path.join(repo, LOCAL_SETTINGS_REL)
    if os.path.islink(path) or not os.path.isfile(path):
        return []  # absent, or a link mir will not follow to inspect
    try:
        with open(path, encoding="utf-8") as f:
            settings = json.load(f)
    except (OSError, UnicodeDecodeError, ValueError) as e:
        return ["%s could not be read as JSON (%s), so mir could not check it for a stale "
                "mir-tagged hook. mir does not own this file and will not fix it for you."
                % (LOCAL_SETTINGS_REL, e)]
    if not isinstance(settings, dict):
        return []
    hooks = settings.get("hooks")
    pre = hooks.get("PreToolUse") if isinstance(hooks, dict) else None
    if not isinstance(pre, list):
        return []

    cmd = claude_guard_command(guard_rel)
    findings = []
    for entry in pre:
        if not isinstance(entry, dict) or not _mir_hook_entry(entry, cmd, guard_rel):
            continue
        matcher = entry.get("matcher")
        entry_hooks = entry.get("hooks") if isinstance(entry.get("hooks"), list) else []
        cmds = [h.get("command") for h in entry_hooks if isinstance(h, dict)]
        if matcher == MATCHER and cmd in cmds:
            continue  # this entry is exactly the desired shape: nothing to report
        findings.append(
            "%s has a mir-tagged PreToolUse hook that is STALE: matcher=%r, command(s)=%r "
            "-- does not match the desired matcher %r / command %r. mir will not rewrite "
            "this file (it is conventionally gitignored and per-developer); fix the entry "
            "by hand, or delete it and re-run `mir init` so the guard actually fires."
            % (LOCAL_SETTINGS_REL, matcher, cmds, MATCHER, cmd))
    return findings


def _preserve_tail(dest: str, disposition: str, new_content: str) -> str:
    """Keep whatever the human wrote below the tail marker, in EVERY artifact that has one.

    This used to be hard-coded to `rel != "AGENTS.md"`, so CLAUDE.md carried an ownership
    marker that meant nothing -- the file was rewritten whole despite being documented as
    having room for repo notes. The rule is now derived from the content mir is about to
    write: an artifact that emits the tail marker gets tail preservation, which is what makes
    a sixth artifact covered the day it is added rather than the day someone remembers.
    """
    if TAIL_MARK not in new_content:
        return new_content
    if disposition != MIR_OWNED:
        return new_content              # absent, or refused; there is no tail to keep
    with open(dest, encoding="utf-8") as f:
        old = f.read()
    if TAIL_MARK not in old:
        return new_content
    tail = old.split(TAIL_MARK, 1)[1]
    return new_content + tail.lstrip("\n")


def _refusal_report(refusals: list) -> str:
    lines = ["refusing to write %d destination(s) mir does not own:" % len(refusals)]
    for d, backup in refusals:
        lines.append("  %s -- %s" % (d.rel, d.detail))
        if backup:
            lines.append("      a copy was saved to %s" % backup)
    lines.append("Move or remove the file(s), or point mir at a different repo, and re-run.")
    return "\n".join(lines)


def apply(repo: str, items: list[dict]) -> list[str]:
    """Write the plan, or write none of it.

    Every destination is inspected before the first byte lands, because a run that aborts
    halfway leaves a harness that looks installed and enforces nothing -- worse than no
    harness at all, which at least tells the truth.
    """
    dispositions = {}
    refused = []
    for it in items:
        d = inspect_destination(repo, it["path"])
        dispositions[it["path"]] = d
        if d.refused:
            refused.append(d)
    if refused:
        # Back up only now, and only the regular files whose content is at stake: a symlink
        # or a device node is refused precisely because reading it is the hazard.
        pairs = [(d, _backup(d.path) if d.state in BACKED_UP else "") for d in refused]
        raise GenerateError(_refusal_report(pairs))

    written = []
    for it in items:
        dest = os.path.join(repo, it["path"])
        parent = os.path.dirname(dest)
        if parent:
            os.makedirs(parent, exist_ok=True)
        content = _preserve_tail(dest, dispositions[it["path"]].state, it["content"])
        _write_owned(dest, content)
        written.append(it["path"])
    return written
