"""Emit the per-project artifacts: manifest, guard, hooks, thin AGENTS.md, CLAUDE.md.

Design rules that came straight out of the plan reviews:
  - AGENTS.md stays THIN (EXTENDING.md Rule 2): it names the pillars that apply and the one
    hard rule, and defers all depth to the skills. It never inlines skill content.
  - .claude/settings.json is MERGED, not overwritten: an existing hook set is preserved and
    the mir hook is added once, tagged, so re-running is idempotent.
  - Every generated file carries an ownership marker so a human and a re-run both know mir
    owns it. Content below the marker in AGENTS.md is preserved on regceneration.
  - --dry-run prints the diff of what would change and writes nothing.
"""

from __future__ import annotations

import json
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
import schema  # noqa: E402

MARK = "generated by mir init"
HOOK_TAG = "mir-init-guard"
MATCHER = "Write|Edit|MultiEdit|NotebookEdit|Update|Bash"


def _pillars(resolved: list[str]) -> list[str]:
    return [s for s in resolved if s.count("-") == 1]


def thin_agents_md(repo_name: str, resolved: list[str], answers: dict, stamp: str) -> str:
    pillars = _pillars(resolved)
    stack_lines = []
    for pillar, choice in answers.items():
        vals = choice if isinstance(choice, list) else [choice]
        stack_lines.append(f"- {pillar}: {', '.join(vals)}")
    lines = [
        f"# {repo_name} — Make It Right baseline",
        "",
        "> AI makes it work. Make It Right. This file only names the disciplines that apply",
        "> here; the depth lives in the `mir-*` skills, which load on demand. Keep it thin —",
        "> never paste skill content into this file (it is billed on every request).",
        "",
        "## The one hard rule",
        "Do not write implementation code until constraints are discovered, assumptions are",
        "confirmed, and the design is approved. On ambiguity, stop and ask.",
        "",
        "## Pillars that apply to this repo",
    ]
    for p in pillars:
        lines.append(f"- `{p}` — loads on a matching task")
    lines += [
        "",
        f"## Stack (chosen via mir init, {stamp})",
        *(stack_lines or ["- (none recorded)"]),
        "",
        "## Write policy",
        "Writes are constrained by `.mir/manifest.json` and enforced by `.mir/guard.py`",
        "(a PreToolUse hook registered in `.claude/settings.json`). Denied: secrets, `.git`,",
        "home config, the policy itself. Run `python3 .mir/probe.py --repo .` to check it.",
        "",
        f"<!-- {MARK}; owned_by_mir. Re-run `mir init` to regenerate ABOVE this line. -->",
        "<!-- Anything you write BELOW this line is preserved across regenerations. -->",
        "",
    ]
    return "\n".join(lines)


def claude_md() -> str:
    return (
        "@AGENTS.md\n\n"
        f"<!-- {MARK}: this imports the thin baseline above. Add repo-specific notes below. -->\n"
    )


def merge_settings(existing: dict | None, guard_rel: str) -> tuple[dict, bool]:
    """Add the mir PreToolUse hook once. Returns (settings, changed)."""
    settings = dict(existing or {})
    hooks = settings.setdefault("hooks", {})
    pre = hooks.setdefault("PreToolUse", [])
    cmd = f'python3 "$CLAUDE_PROJECT_DIR/{guard_rel}"'
    for entry in pre:
        for h in entry.get("hooks", []):
            if h.get("command") == cmd or HOOK_TAG in json.dumps(entry):
                return settings, False  # already present
    pre.append({
        "matcher": MATCHER,
        "_mir": HOOK_TAG,
        "hooks": [{"type": "command", "command": cmd}],
    })
    return settings, True


def plan(repo: str, resolved: list[str], answers: dict, stamp: str) -> list[dict]:
    """Compute the file writes without performing them. Each item: {path, content, note}."""
    repo_name = os.path.basename(os.path.abspath(repo))
    items: list[dict] = []

    manifest = schema.project_manifest(repo_name, allowed_write_roots=["."])
    manifest["generated_at"] = stamp
    manifest["stack"] = answers
    manifest["skills"] = resolved
    items.append({"path": ".mir/manifest.json",
                  "content": json.dumps(manifest, indent=2) + "\n", "note": "project policy"})

    # All mir-owned files live under .mir/, which is a denied path -- so the agent cannot
    # rewrite the guard, probe, or manifest to widen its own permissions.
    with open(os.path.join(HERE, "guard.py"), encoding="utf-8") as f:
        items.append({"path": ".mir/guard.py", "content": f.read(),
                      "note": "the enforcing hook (copied, self-protected under .mir/)"})
    with open(os.path.join(HERE, "probe.py"), encoding="utf-8") as f:
        items.append({"path": ".mir/probe.py", "content": f.read(),
                      "note": "manifest-derived verifier"})

    settings_path = os.path.join(repo, ".claude", "settings.json")
    existing = None
    if os.path.exists(settings_path):
        try:
            existing = json.load(open(settings_path, encoding="utf-8"))
        except Exception:
            existing = None
    settings, changed = merge_settings(existing, ".mir/guard.py")
    if changed:
        items.append({"path": ".claude/settings.json",
                      "content": json.dumps(settings, indent=2) + "\n",
                      "note": "PreToolUse hook (merged)" if existing else "PreToolUse hook"})

    items.append({"path": "AGENTS.md",
                  "content": thin_agents_md(repo_name, resolved, answers, stamp),
                  "note": "thin baseline (regenerates above the marker)"})
    items.append({"path": "CLAUDE.md", "content": claude_md(), "note": "imports AGENTS.md"})
    return items


def install_project_skills(repo: str, resolved: list[str], repo_dir: str) -> list[str]:
    """Symlink this repo's tiers/modules into <repo>/.claude/skills/.

    Claude Code merges ~/.claude/skills with <repo>/.claude/skills, so with a global
    install of --scope=pillars the repo ends up with exactly: the 7 pillars (everywhere)
    plus the handful of tiers/modules this repo actually uses. A repo that never runs
    mir init still gets the pillar gates, which is the right graceful degradation.

    Depth-1 slugs are skipped: they are the global floor, and personal skills take
    precedence over project skills anyway, so a local copy would be shadowed.
    """
    dest_dir = os.path.join(repo, ".claude", "skills")
    os.makedirs(dest_dir, exist_ok=True)
    linked = []
    for slug in resolved:
        if slug.count("-") <= 1:
            continue                      # pillar: lives in the global floor
        src = os.path.join(repo_dir, "skills", slug)
        if not os.path.isdir(src):
            continue
        dst = os.path.join(dest_dir, slug)
        if os.path.exists(dst) and not os.path.islink(dst):
            continue                      # never clobber a real directory
        if os.path.islink(dst) or os.path.exists(dst):
            os.unlink(dst)
        os.symlink(src, dst)
        linked.append(slug)
    return linked


def prune_project_skills(repo: str, keep: list[str]) -> list[str]:
    """Remove mir-* symlinks in <repo>/.claude/skills that are no longer resolved.

    Without this, re-running mir init after a stack change leaves the old stack's skills
    loading forever -- the exact context creep this feature exists to remove.
    """
    dest_dir = os.path.join(repo, ".claude", "skills")
    if not os.path.isdir(dest_dir):
        return []
    keep_set = set(keep)
    removed = []
    for name in sorted(os.listdir(dest_dir)):
        if not name.startswith("mir-"):
            continue
        p = os.path.join(dest_dir, name)
        if os.path.islink(p) and name not in keep_set:
            os.unlink(p)
            removed.append(name)
    return removed


def _preserve_tail(repo: str, rel: str, new_content: str) -> str:
    """For AGENTS.md, keep whatever the human wrote below the preserve marker."""
    if rel != "AGENTS.md":
        return new_content
    path = os.path.join(repo, rel)
    if not os.path.exists(path):
        return new_content
    old = open(path, encoding="utf-8").read()
    marker = "preserved across regenerations. -->"
    if marker in old:
        tail = old.split(marker, 1)[1]
        return new_content + tail.lstrip("\n")
    return new_content


def apply(repo: str, items: list[dict]) -> list[str]:
    written = []
    for it in items:
        dest = os.path.join(repo, it["path"])
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        content = _preserve_tail(repo, it["path"], it["content"])
        with open(dest, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(it["path"])
    return written
