"""Antigravity: the target whose host fails OPEN, so whose adapter must fail CLOSED.

This is the one place in the tree where mir's usual posture is inverted, and the inversion is
declared here rather than inherited from the base class, because inheriting it silently is
exactly how it would be lost.

Claude Code surfaces a hook error to the user: an adapter that crashes there is loud, so it
may allow the write and let the human see the failure. Antigravity LOGS a hook error and
SKIPS the hook -- a nonzero exit, an uncompilable matcher, a timeout, any of them -- and the
write proceeds. Fail-open there is silent. So the adapter:

  - answers on stdout with `{"decision": "deny"}` and exit 0, because the host ignores the
    exit code entirely. An adapter that "just exits 2 as well" has enforced nothing;
  - catches everything at the top level and still emits deny-JSON, so a crash denies;
  - imports nothing that may be missing (guard.py is stdlib-only and standalone by design);
  - does no network, no subprocess, and no filesystem work beyond reading one JSON manifest,
    which keeps it far under the 30s default hook timeout. A timeout is a skipped hook.

`"matcher": "*"`, not an enumerated list. Matchers compile anchored `^(?:...)$`, and the
write surface here is wider than the three obvious tools: the shipped binary also carries
`sed_file`, `notebook_edit`, a `delete_file` proto field, and arbitrary MCP tools reached
through `call_mcp_tool`. Enumerating three names is a hole with a tidy list in front of it.

Everything about whether the host actually invokes `.agents/hooks.json` and honours the deny
is unverified -- GOAL.md B1.10 names the 3-phase manual procedure. Until someone runs it, the
level here is `unverified`, and COVERAGE.md says which claim that leaves unmade.
"""

from __future__ import annotations

import json

from .base import Capability, Context, Target

HOOK_TAG = "mir-init-guard"
HOOKS_REL = ".agents/hooks.json"

# Every tool. See the module docstring: three names is a hole, not a list.
MATCHER = "*"

# The write tools the adapter maps by name. NOT the matcher -- the matcher is `*` and this is
# only the set whose argument shape the guard knows how to read a target out of. A tool
# outside this set still reaches the guard, which falls back to reading path-shaped arguments
# and reports partial coverage, rather than allowing it unread.
FILE_WRITE_TOOLS = ("write_to_file", "replace_file_content", "multi_replace_file_content")
COMMAND_TOOLS = ("run_command",)


def guard_command(guard_rel: str = ".mir/guard.py") -> str:
    """Relative for the same reason Codex's is: an unset `$SOMETHING_PROJECT_DIR` expands to
    the empty string and turns the command into `/.mir/guard.py`, which is a hook that fails
    -- and on this host a failed hook is a skipped hook, which is an allowed write."""
    return "python3 %s --protocol antigravity" % guard_rel


def hooks_document(guard_rel: str = ".mir/guard.py") -> dict:
    return {"hooks": {"PreToolUse": [{
        "matcher": MATCHER,
        "_mir": HOOK_TAG,
        "_generated_by": "generated by mir init",
        "hooks": [{"type": "command", "command": guard_command(guard_rel)}],
    }]}}


class AntigravityTarget(Target):
    name = "antigravity"
    guard_protocol = "antigravity"
    wiring_files = (HOOKS_REL,)
    # THE INVERSION. Declared, never inherited: the host logs a hook error and continues, so
    # an adapter that fails open here fails open silently and the write lands.
    fail_open = False
    summary = ("Antigravity: PreToolUse hook in .agents/hooks.json, denies via stdout JSON "
               "with exit 0 (the host ignores the exit code)")

    capabilities = {
        "skills": Capability(
            level="enforced",
            mechanism="~/.gemini/config/skills, symlinked by install.sh --tool=antigravity",
            source="runtime allowlist in the shipped binaries, verified 2026-08-25 "
                   "(docs/v2-plan.md D6)",
            caveats=("the legacy ~/.gemini/antigravity/skills path is never scanned; "
                     "a populated directory was mistaken for a live one for a whole release",),
        ),
        "subagents": Capability(
            level="unverified",
            mechanism="no path for standalone sub-agent definitions has been confirmed, so "
                      "mir emits none",
            source="docs/v2-plan.md Q2, 'Still unresolved'",
            caveats=("NOT PROVEN: whether subagent tool calls route through the same hook "
                     "wrapper. If they do not, a subagent's writes bypass the guard entirely",),
        ),
        "always_on_context": Capability(
            level="enforced",
            mechanism="root AGENTS.md as a rule file",
            source="https://antigravity.google/docs",
            caveats=("per-rule-file cap of 12,000 characters -- the tightest of the three "
                     "hosts, so it is the limit AGENTS.md is tested against",),
        ),
        "write_policy_enforcement": Capability(
            level="unverified",
            mechanism=".agents/hooks.json PreToolUse entry with matcher `*`, running "
                      "`python3 .mir/guard.py --protocol antigravity`; denies with "
                      "{\"decision\": \"deny\"} on stdout and exit 0",
            source="https://antigravity.google/docs (hooks); binary inspection for the "
                   "PreToolUse fire-on-file-write behaviour, docs/v2-plan.md Q2",
            caveats=(
                "NOT PROVEN: that Antigravity invokes .agents/hooks.json and honours the "
                "deny. GOAL.md B1.10 names the 3-phase fire / deny / fail-open procedure",
                "the HOST fails open on a hook error, so the adapter is fail-closed by "
                "construction -- a crash emits deny-JSON rather than nothing",
                "one exception, stated rather than hidden: a manifest version the guard does "
                "not understand still fails OPEN on every protocol, because a colleague's "
                "newer manifest must not brick this repo's agent. Regenerate with `mir init`",
                "coverage for tools outside the known write set is PARTIAL: the guard reads "
                "path-shaped arguments off an unrecognised tool rather than allowing it",
            ),
        ),
    }

    def guard_command(self) -> str:
        return guard_command()

    def plan_items(self, ctx: Context) -> list:
        return [{"path": HOOKS_REL,
                 "content": json.dumps(hooks_document(ctx.guard_rel), indent=2) + "\n",
                 "note": "PreToolUse hook (Antigravity; denies via stdout JSON, exit 0)"}]

    def notes(self, ctx: Context) -> list:
        return ["Antigravity: `.agents/hooks.json` was written and `.agents` is denied "
                "wholesale by the policy, so the agent cannot unregister its own guard. "
                "Whether the host invokes it is UNVERIFIED -- run the 3-phase check in "
                ".mir/COVERAGE.md."]
