"""OpenAI Codex: same hook shape as Claude Code, one extra write surface, one real loss.

Three facts drive everything in this file:

  1. Codex hooks use the same event -> matcher -> handler shape and the same stdin field
     names as Claude Code, and block on exit 2 with a reason on stderr. That is why the
     codex adapter in guard.py reuses the claude event parser instead of duplicating it.
  2. Codex intercepts `apply_patch`, which Claude Code has no equivalent of. The patch body
     names its own files in `*** Add File:` / `*** Update File:` / `*** Delete File:`
     headers, so the guard parses them -- and an UNPARSEABLE body returns deny, never `ask`.
     Codex treats an unsupported decision as "continue", so `ask` is fail-OPEN wearing a
     careful decision's clothes.
  3. Codex has no directory for standalone sub-agent definitions. Earlier empirical probing
     planted agent .md files in four candidate locations and none of them loaded, so this
     target emits no agent files at all rather than inventing a path. See agents_export.py.

Everything about whether Codex ACTUALLY invokes a repo-local `.codex/hooks.json` -- and
whether it demands a trust approval first -- is unverified here, which is why
write_policy_enforcement is `unverified` and not `enforced`. The file being emitted is not
evidence that anything reads it; that confusion is defect D6, and it cost a whole release.
"""

from __future__ import annotations

import json

from .base import Capability, Context, Target

HOOK_TAG = "mir-init-guard"
HOOKS_REL = ".codex/hooks.json"

# The same tool set Claude Code's matcher names, plus apply_patch -- the Codex-only write
# surface. Enumerated rather than `*` because Codex's documented matcher is a tool-name
# alternation and the guard's own PATH_FIELD_TOOLS is the list it can actually read a path
# out of. Antigravity gets `*` for the opposite reason; see antigravity.py.
MATCHER = "Write|Edit|MultiEdit|NotebookEdit|Update|Bash|apply_patch"


def guard_command(guard_rel: str = ".mir/guard.py") -> str:
    """Relative, not `$SOMETHING_PROJECT_DIR`.

    Claude Code documents `$CLAUDE_PROJECT_DIR`; no equivalent is verified for Codex, and an
    unset variable expands to the empty string, which turns the command into `/.mir/guard.py`
    -- a path that does not exist, on a hook that then fails. A relative path assumes the host
    runs hooks with the project root as cwd. That assumption is NOT verified either, so it is
    written into COVERAGE.md as a manual check rather than left implicit here.
    """
    return "python3 %s --protocol codex" % guard_rel


def hooks_document(guard_rel: str = ".mir/guard.py") -> dict:
    """The `.codex/hooks.json` mir writes.

    `_mir` and `_generated_by` sit on the ENTRY, not at the top level, for two reasons: it is
    the shape mir already uses in `.claude/settings.json`, and generate.inspect_destination
    proves ownership by finding the marker string anywhere in the file's bytes. A top-level
    key nothing recognises is a bigger bet on a host schema mir does not own.
    """
    return {"hooks": {"PreToolUse": [{
        "matcher": MATCHER,
        "_mir": HOOK_TAG,
        "_generated_by": "generated by mir init",
        "hooks": [{"type": "command", "command": guard_command(guard_rel)}],
    }]}}


class CodexTarget(Target):
    name = "codex"
    guard_protocol = "codex"
    wiring_files = (HOOKS_REL,)
    fail_open = True     # blocks on exit 2, and a nonzero exit is visible to the user
    summary = "Codex: PreToolUse hook in .codex/hooks.json, blocks on exit 2"

    capabilities = {
        "skills": Capability(
            level="advisory",
            mechanism="install.sh --tool=codex prints a NOTE; there is no symlink target "
                      "Codex scans for skill directories",
            source="https://developers.openai.com/codex/",
            caveats=("skills are not installed for Codex; the agent reads AGENTS.md only",),
        ),
        "subagents": Capability(
            level="none",
            mechanism="no directory for standalone sub-agent definitions was found. Agent "
                      ".md files planted in four candidate locations loaded in none of them",
            source="empirical probe, 2026-08-25 (see init/agents_export.py LOSSY_FIELDS)",
            caveats=("the reviewers' `tools:` read-only restriction has no Codex equivalent "
                     "even if a path is found later -- Codex sub-agent TOML has no `tools:` "
                     "field, so the restriction is a real capability loss, not a formatting "
                     "difference",),
        ),
        "always_on_context": Capability(
            level="enforced",
            mechanism="root AGENTS.md, read on every request",
            source="https://developers.openai.com/codex/",
            caveats=("shared with Antigravity and Cursor, so it is written to the tightest "
                     "limit of the three (12,000 chars)",),
        ),
        "write_policy_enforcement": Capability(
            level="unverified",
            mechanism=".codex/hooks.json PreToolUse entry running "
                      "`python3 .mir/guard.py --protocol codex`; blocks on exit 2",
            source="https://developers.openai.com/codex/",
            caveats=(
                "NOT PROVEN: that Codex invokes a repo-local .codex/hooks.json at all",
                "NOT PROVEN: whether a per-hook trust approval is required first. If it is, "
                "an unapproved hook is an emitted file nothing runs",
                "NOT PROVEN: that hooks run with the project root as cwd, which the relative "
                "command assumes",
                "apply_patch bodies are parsed for their own file headers; a body that will "
                "not parse returns deny, because `ask` is a decision Codex continues past",
            ),
        ),
    }

    def guard_command(self) -> str:
        return guard_command()

    def plan_items(self, ctx: Context) -> list:
        return [{"path": HOOKS_REL,
                 "content": json.dumps(hooks_document(ctx.guard_rel), indent=2) + "\n",
                 "note": "PreToolUse hook (Codex; blocks on exit 2)"}]

    def notes(self, ctx: Context) -> list:
        return ["Codex: `.codex/hooks.json` was written. Nothing in this repository can prove "
                "Codex reads it -- run the trust-approval check in .mir/COVERAGE.md before "
                "relying on it."]
